"""Persistence contracts shared by the Postgres catalog and callers."""

from collections.abc import Mapping
from datetime import date
from typing import Any, Protocol


class CatalogRepository(Protocol):
    """Async contract for document, chunk and feedback persistence."""

    async def initialize(self) -> None: ...

    async def is_ready(self) -> bool: ...

    async def get_file(self, doc_id: str, visitor_id: str | None = None) -> dict[str, Any] | None: ...

    async def create_document(self, record: Mapping[str, Any]) -> dict[str, Any]: ...

    async def create_document_with_quota(
        self, record: Mapping[str, Any], client_hash: str, usage_date: date
    ) -> dict[str, Any]: ...

    async def create_processing_file(self, record: Mapping[str, Any]) -> dict[str, Any]: ...

    async def find_by_sha256(self, sha256: str, visitor_id: str | None = None) -> dict[str, Any] | None: ...

    async def update_status(
        self,
        doc_id: str,
        status: str,
        *,
        chunks_count: int = 0,
        warnings: list[str] | None = None,
        error_message: str | None = None,
    ) -> None: ...

    async def update_file_status(
        self,
        doc_id: str,
        status: str,
        *,
        chunks_count: int = 0,
        warnings: list[str] | None = None,
        error_message: str | None = None,
    ) -> None: ...

    async def mark_uploaded(self, doc_id: str, visitor_id: str | None = None) -> bool: ...

    async def renew_upload(self, doc_id: str, expires_at: Any, visitor_id: str | None = None) -> None: ...

    async def claim_processing(self, doc_id: str, visitor_id: str | None = None) -> bool: ...

    async def claim_retry(self, doc_id: str) -> bool: ...

    async def list_documents(self) -> list[dict[str, Any]]: ...

    async def register_chunks(self, chunks: list[dict[str, Any]]) -> None: ...

    async def register_objects(self, objects: list[dict[str, Any]]) -> dict[str, str]: ...

    async def clear_processing_artifacts(self, doc_id: str) -> None: ...

    async def valid_chunk_refs(self, refs: list[dict[str, str]]) -> set[str]: ...

    async def owned_chunk_ids(self, chunk_ids: list[str], visitor_id: str) -> set[str]: ...

    async def add_chunks(self, chunks: list[dict[str, Any]]) -> None: ...

    async def record_feedback(
        self, visitor_id: str, response_id: str, useful: bool
    ) -> str: ...

    async def persist_generated_response(
        self, visitor_id: str, question: str, answer: str, source_ids: list[str], sources: list[dict[str, Any]], insufficient_context: bool, conversation_id: str | None = None
    ) -> dict[str, str]: ...

    async def create_conversation(self, visitor_id: str, conversation_id: str | None = None) -> str: ...

    async def get_conversation(self, visitor_id: str, conversation_id: str) -> list[dict[str, Any]] | None: ...

    async def get_message(self, visitor_id: str, message_id: str) -> dict[str, Any] | None: ...

    async def record_message(
        self, visitor_id: str, conversation_id: str, question: str, answer: str, source_ids: list[str], sources: list[dict[str, Any]], insufficient_context: bool
    ) -> str: ...

    async def delete_conversation(self, visitor_id: str, conversation_id: str) -> bool: ...

    async def get_statistics(self) -> dict[str, Any]: ...

    async def remove_document(self, doc_id: str) -> None: ...

    async def delete_file(self, doc_id: str) -> None: ...

    async def get_vector_ids(self, doc_id: str) -> list[str]: ...

    async def get_object_keys(self, doc_id: str) -> list[str]: ...

    async def begin_deletion(self, doc_id: str, lease_seconds: int = 120) -> dict[str, Any]: ...

    async def mark_deletion_stage(
        self, doc_id: str, stage: str, *, error: str | None = None, lease_seconds: int = 120
    ) -> None: ...

    async def complete_deletion(self, doc_id: str) -> None: ...

    async def list_expired_documents(self, limit: int, older_than: Any = ...) -> list[dict[str, Any]]: ...

    async def list_deleting_documents(self, limit: int) -> list[dict[str, Any]]: ...

    async def list_all_documents(self) -> list[dict[str, Any]]: ...

    async def record_audit_event(self, event_type: str, safe_details: Mapping[str, Any] | None = None) -> str: ...

    async def delete_chunks(self, doc_id: str) -> None: ...

    async def list_files(self, visitor_id: str | None = None) -> list[dict[str, Any]]: ...

    async def stats(self) -> dict[str, Any]: ...

    async def clear_catalog(self) -> None: ...

    async def increment_usage(
        self, client_hash: str, usage_date: Any, *, uploads: int = 0, queries: int = 0, bytes_uploaded: int = 0
    ) -> dict[str, Any]: ...

    async def reserve_query_quota(self, client_hash: str, usage_date: date) -> dict[str, Any]: ...

    async def record_ingestion_event(
        self, event_type: str, document_id: str, safe_details: Mapping[str, Any] | None = None
    ) -> str: ...
